### ISSUE TITLE
Function logDebug in sample script does not exist in Grenton

### ISSUE THREAD

**Issue by pidzama** [jnalepka/grenton-to-homeassistant#20]
It seems that function `logDebug` should be replaced with `print` in the sample script in the Readme file. Otherwise the sample does not work out of the box and HA receives HTTP 500 with no hint what is going on.

**Comment by jnalepka** [comment]
Right, `print` would be universal. `lodDebug` works only with the GateHttp 1.4 update and requires DEBUG logging enabled in the OM.
